### PR TITLE
fix to inexistent

### PR DESCRIPTION
**Pull request by mezysinc**

### CODE REVIEW

**Comment by mezysinc** [comment]
fix screenshot as well, this doesn't exist

**Comment by TrianguloY** [comment]
Hmm, what is the reasoning for this change? Both numbers (old and new) seem to not be valid. Is the previous similar to an existing one? 

Also, why not using 55 75 123456789 like other languages?

**Comment by mezysinc** [comment]
Well for me it doesn't really matter but there was that one comment (possibly troll) that said that it was his number (read comments in ptbr)

Why not 123456789. Well long story, to make it short, few years ago lots of numbers had 8 digits and to standardise them gov added "9" to all of them to make it even across entire country. Lots of people got confused by it & to this very day forget to (or doesn't want to) add "9" in front of 8 digit numbers and complain that numbers don't work, mostly ppl from rural and small towns but big cities as well (they even keep on giving away 8 digit numbers and say that 9 "is obvious" so they don't mention that, for wa I guess must be too lol). You have to make it visual and simple so that some of less technical ppl can understand how to go about it, lots of people get confused by almost any small technical issue. You can leave it as it is but read first sentence again just to be sure. The number I changed to doesn't exist because most start with 999, 998 etc, well it wasn't short after all lol

**Comment by TrianguloY** [comment]
Ah, yes, I've seen that comment but though it was referring to the recents list (maybe tried it's own number and then saw it was in the list). I'll try to ask to be sure.

Thanks for the detailed explanation on the number format! In that case, could 55 75 912345678 be a good alternative?

**Comment by mezysinc** [comment]
It looks better & doesn't exist, I changed to that

**Comment by TrianguloY** [comment]
The user haven't replied back yet, so I assume it was a misunderstanding (or a trolling).
In any case I'm merging these changes for consistency, thanks. They will be available on the next version...which hopefully won't take such a long time like the previous one...hopefully.

**Pull request merged**
