### PR TITLE
Hindi Translation added

### PR DESCRIPTION
**Pull request by RaviDhoriya**

### CODE REVIEW

**Comment by TrianguloY** [comment]
Nice! Thank you very much for the translation (and even for the typo fix, which I haven't noticed since forever, for some reason).
I'll review it in the following days/weekend and will notify you.

**Comment by TrianguloY** [comment]
OK!
The update seems fine in almost everything, just a couple issues. I can fix some of them but others require your assistance:
- You kept the UK sample `+44 (UK) 123 456 7890 के लिये 44 1234567890`. Is there a better example for your country? Maybe `+91 (India) 123-4567-890 के लिये 91 1234567890`?
- You also kept the english country code wikipedia link `https://en.wikipedia.org/wiki/List_of_country_calling_codes#Alphabetical_listing_by_country_or_region`. I don't see an Hindi translation for that page, but maybe you know of another wikipedia-like site with it? (which is a standard more or less, not an unknown blog somewhere)
- The CDATA part in hint_prefAndNumber is misleading, I'm going to try to remove it. You do need to translate the content inside: `Pref & Number`

I'll leave this request open so you can update it simply by commiting to your branch. I'll merge it afterwards.

**Comment by RaviDhoriya** [comment]
@TrianguloY fixed example as per the comment, it makes more sense now.
For Country calling code list, wiki does have hindi version of same page. Its just that country list isn't in tabular format. Please check that and see if its good to use. Otherwise can try finding other places.

**Comment by TrianguloY** [comment]
That url is perfect, no need to find another one.

Note: You didn't translate the `Pref & Number` part, simply paste it inside the CDATA (or rather remove the CDATA altogether ). If you are unsure just write the translation as a comment here and I'll paste it in the correct format after the merge.

**Comment by RaviDhoriya** [comment]
I thought I need to keep CDATA as is. Just translated it now. 

I leave it up to you, either keep it or remove it. :)

**Pull request merged**
