### PR TITLE
updated strings

### PR DESCRIPTION
**Pull request by mezysinc**
and few fixes

### CODE REVIEW

**Comment by mezysinc** [comment]
Que tal, como te va ? ;

I saw few feedbacks on ggl.ply.str saying that "app didn't work" so for that reason I rewrite the part with how you should input the phone number. This will most likely solve all that "unjust" low feedback.

and it would be good to update screenshots on ggl.ply.str again so that it can be displayed in correct way (or whatever u decide ;)

ok have a nice weekend

**Comment by TrianguloY** [comment]
A bit busy as you can see. Give me a few more days for a proper review and response 🙇‍♂️

**Comment by TrianguloY** [comment]
My apologies for the really late reply.

Hi! Nice to see you again on GitHub. The number of complains about 'it doesn't work' is notable, yes, in fact I remember updating recently the app to include a link to WhatsApp official help (not sure if it helped or not). I see you specified the need to include an area code, I think that's a good idea, let's hope it helps other users.

The rest of the updates seems ok, merged!

I'll upload the changes of the Play Store page shortly after this message, so it should be available in a few hours. As for the app, I want to include a small change in the next version, so I hope I'll be able to do it soon and upload both changes at the same time. Otherwise I'll simply publish a 'translations updated' version and leave the other for the future.

**Comment by mezysinc** [comment]
looks good, on the last screenshot should be 'do' not 'de'; if you add some new strings let me know. Have a good wkend ;

**Comment by TrianguloY** [comment]
@mezysinc Just in case you missed it (and because you wanted to be notified of new translations) please check https://github.com/TrianguloY/OpenInWhatsapp_Translation/issues/28#issuecomment-869842070 for a new string.

**Comment by mezysinc** [comment]
Yep, it's below:

`Otimizada opção de colar com entradas agregadas`

Have a good one, if you need more @ at me ; because I'm don't subscribe to threads

**Comment by TrianguloY** [comment]
Got it! 
Thanks

**Comment by mezysinc** [comment]
@TrianguloY some reviews are pretty interesting, see below ( [pt] tirou = sacó [es] )

medical use


now you can publish it in health section ;

**Comment by mezysinc** [comment]
@TrianguloY 
Looks to me like it was some trolling in the end & ___ attacking you (via var. accounts, not going to mention name because feeding animals is dangerous), ... those ppl are so sad, utter sadness ...

**Comment by TrianguloY** [comment]
I have the impression it was a misunderstanding. In either case don't worry, a bad review is not a big deal.
I've been out of home these days, hopefully this weekend the update will be released.

**Comment by TrianguloY** [comment]
@mezysinc https://github.com/TrianguloY/OpenInWhatsapp_Translation/issues/28#issuecomment-886023450

**Comment by mezysinc** [comment]
`Mostrar a mensagem 'verificar o prefixo' digitado em linha`

Have a good one ;

**Comment by TrianguloY** [comment]
@mezysinc https://github.com/TrianguloY/OpenInWhatsapp_Translation/issues/28#issuecomment-886170306
Sorry for the second ping so soon, but I'm going to try to push this change too.

**Comment by mezysinc** [comment]
`Novo modo de abrir: valores predefinidos` (for changelog)


`Predefinido: Garante que funciona com o Whatsapp oficial e Business.` (for settings)

**Comment by TrianguloY** [comment]
@mezysinc V 3.3 https://github.com/TrianguloY/OpenInWhatsapp_Translation/issues/28#issuecomment-894775056

**Comment by mezysinc** [comment]
- Nova tradução em malaiala. Obrigado Thenur Mahesh Kannan!
- Links de compartilhamento via 'https://'
- Exclusão de zeros precedentes em modo agregado

**Pull request merged**
