### PR TITLE
Added Tamil translations

### PR DESCRIPTION
**Pull request by mage1k99**
I've Added Tamil translation in Playstore/ta_in, res/raw-ta/countries_name.txt, values-ta/strings.xml

### CODE REVIEW

**Comment by TrianguloY** [comment]
Thank you!
As soon as I revise them I'll merge and publish an update.
But note that it may take a few days (due to the festive season).

**Comment by mage1k99** [comment]
Thank you so much !

**Comment by TrianguloY** [comment]
Thank to you for the translation!
As you may saw the update is already on the beta, will be pushed to stable tomorrow probably.

About the Play Store translation, I'm afraid I can't publish it. Play Store has a character limit (80 characters for the description_short, 4000 for the description_long) and your translation has 82 and 4525 respectively. Do you think you could change them a bit? maybe use synonyms or similar sentences. For the description_long you can remove the second block _"What is this app ... not storage, nothing. Check it! )."_ if you need. 
Also, don't forget to add you name in the list of names at the bottom! (in the description_long I mean)

@mage1k99

**Comment by mage1k99** [comment]
Thank you for publishing! , If i change the translation as per the character limit and create a pull request will you merge and publish again ?

**Pull request merged**
