### PR TITLE
Updated Russian language 2.8

### PR DESCRIPTION
**Pull request by solokot**

### CODE REVIEW

**Comment by TrianguloY** [comment]
Perfect! Sorry for the delay, expect the update soon!
Just one confirmation: You translated the 'donation' texts. Just to be sure: 
Is it ok for me to show them in the russian translation?

(I just want to have the translator permission, is all, ans also because I said it: https://github.com/TrianguloY/OpenInWhatsapp_Translation/blob/a5a77dbe5d68ad4130174deef866be73009c3bc7/res/values/strings.xml#L33)

**Comment by solokot** [comment]
> You translated the 'donation' texts.
> will only be visible on translations where I had permission from the translator itself
Why not? Application development requires much more effort than translation.
On the other hand, it is hardly worth waiting for anything from Russia in terms of donations (the situation leaves much to be desired).

> Agenda
Of course, I saw the new functionality in the list, but I see no reason to change the previous translation (the literal translation "Last Numbers"), it perfectly conveys the essence of this list.

**Comment by abeln94** [comment]
Perfect thanks. Donations in general aren't very common (hardly one per month) but for me it's more the intention than the amount.

The change was to empathize you can now pin numbers, but it's true that it is basically the old list with a bit more features. Ok, I'll keep it and set it in the title too.


If nothing breaks horribly (and it shouldn't) the update should be available tomorrow.

**Comment by TrianguloY** [comment]
Perfect thanks. Donations in general aren't very common (hardly one per month) but for me it's more the intention than the amount.

The change was to empathize you can now pin numbers, but it's true that it is basically the old list with a bit more features. Ok, I'll keep it and set it in the title too.


If nothing breaks horribly (and it shouldn't) the update should be available tomorrow.

**Pull request merged**
