### PR TITLE
Russian translation clipboard toast

### PR DESCRIPTION
**Pull request by solokot**

### CODE REVIEW

**Comment by TrianguloY** [comment]
Thanks, but as I said I'm currently refactoring all the Play Store texts (btw, your description was longer than the maximum permitted, so I needed to cut it), and also there are some more strings that will need translation.

Since this pull request is just one line, please wait until all the new data is uploaded (I'll notify here) so you can translate the final version (you may need to merge the changes in your fork, so if you need to discard this changes and open a new pull request don't worry).

**Comment by TrianguloY** [comment]
Done, you can translate everything now.

There is something more I want to add, but that will probably be added on the next version. I need to wait until Play Store approves these changes first, and that may take a while.

**Comment by TrianguloY** [comment]
Hi, are you still working on the changes? I would like to publish the version tonight (+9 hours from now), so if possible try to translate the new strings before then.

If you are busy and can't don't worry, I'll merge this change and just create a new pull request next week or when needed.

**Comment by solokot** [comment]
Hey!
Just today I had time, so in an hour or two, I think it will be ready. If I don’t have time, then it will work out by the next version, it’s not scary.
Thanks for the info!

**Pull request closed without merging**
